### PR TITLE
slice supported for generator

### PR DESCRIPTION
**Pull request by xuwei0455**
I have check the code, and nothing error go.
I suppose it may cause by diff of master and dev, so i create this pr without any changes.
*************
add slice support for Generator;

so we can use like follows:
```
for ans in me.answers.order_by('votenum')[:10]:
    print(ans.question.title, ans.voteup_count)
```

### CODE REVIEW

**Comment by xuwei0455** [comment]
I have catch this, it's failed cause of raw code which in TopicActivityGenerator as follows:
```
class TopicActivityGenerator(BaseGenerator):
    def __init__(self, url, session):
        super(TopicActivityGenerator, self).__init__(url, session)

    def _build_obj(self, data):
        answer_list = data.get('answers', [])
        answer_count = len(answer_list)
        if answer_count == 0:
            # Only question
            return build_zhihu_obj_from_dict(data, self._session)
        elif answer_count == 1:
            return build_zhihu_obj_from_dict(answer_list[0], self._session)
        else:
            raise UnimplementedWarning(UnimplementedException(
                'I think question generated by Topic.activities has only '
                'one answer at most, if you see this warning, '
                'which proves that I am wrong, '
                'please open a issue in Github with the data ' + str(data)
            ))
            return None
``` 

The **return None** is unreachable.

**Comment by xuwei0455** [comment]
Obviously, i'm wrong, but i can not find more error out, i think i need some help.

**Comment by 7sDream** [comment]
Because I do not have a computer around, so I can only give you some feasible process.

```bash
sudo pip3 install pep8
cd <project-dir>
pep8 zhihu_oauth
```

Then you can find out the lines cause the CI error.

**Comment by xuwei0455** [comment]
I have fixed the pep8 error, but i got failed in unit test.

It seems can not load token from pickle file？

**Comment by 7sDream** [comment]
Yes, I will fix it tonight.

**Comment by 7sDream** [comment]
Because of Travis CI's security restrictions, PR build can not read the environment variable:

> A pull request sent from a fork of the Eclipse repository could be manipulated to expose any environment variables. The upstream repository's maintainer would have no protection against this attack, as pull requests can be sent by anyone with a fork.
>
> Travis CI makes quantitative variables and data available only to pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.
>
> Pull requests sent from forked repositories do not have access to encrypted variables or data.

(From https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions)

So, I stored the test token file in env var, and the test can't read it, then fail.

This problem can't be solved in this PR, but will be in the future, I will put the token to the yml file in next commit.

Your PR seems no problem now, but I do not have time to review and merge until August.

I'm sorry for you will wait so long, and really thank you for your help and patience.

**Comment by xuwei0455** [comment]
Thanks for your explation, and also for your awesome liabary.

**Comment by 7sDream** [comment]
已 Merge。

但是这种方式其实并没有减少网络请求，所以暂时加了一个 Warning。

> 如果你使用 `followers[10:100]`， 其实前 10 个用户其实也被获取了，并不是最佳用法。推荐使用 `followers.jump(10)[:90]` 这样的写法，会跳过前 10 个用户的网络请求。目前如果 Slice 的 start 不是 0，将会引发 Warning

**Pull request merged**
